config/routes.rb
Rails.application.routes.draw do

  resources :events
  root to: "users#index"

  post 'users/:id/friends/:friend_id' => 'users#add_friend'
  get  'users/:id/friends' => 'users#list_friends'

  resources :friendships
  resources :jsons
  resources :tickets
  resources :ratings
  resources :users

end

app/models/json.rb
class Json < ActiveRecord::Base
end

app/controllers/jsons_controller.rb
class JsonsController < ApplicationController
  before_action :set_json, only: [:show, :edit, :update, :destroy]

  # GET /jsons
  # GET /jsons.json
  def index
    @jsons = Json.all
  end

  # GET /jsons/1
  # GET /jsons/1.json
  def show
  end

  # GET /jsons/new
  def new
    @json = Json.new
  end

  # GET /jsons/1/edit
  def edit
  end

  # POST /jsons
  # POST /jsons.json
  def create
    @json = Json.new(json_params)

    respond_to do |format|
      if @json.save
        format.html { redirect_to @json, notice: 'Json was successfully created.' }
        format.json { render :show, status: :created, location: @json }
      else
        format.html { render :new }
        format.json { render json: @json.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jsons/1
  # PATCH/PUT /jsons/1.json
  def update
    respond_to do |format|
      if @json.update(json_params)
        format.html { redirect_to @json, notice: 'Json was successfully updated.' }
        format.json { render :show, status: :ok, location: @json }
      else
        format.html { render :edit }
        format.json { render json: @json.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jsons/1
  # DELETE /jsons/1.json
  def destroy
    @json.destroy
    respond_to do |format|
      format.html { redirect_to jsons_url, notice: 'Json was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_json
      @json = Json.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def json_params
      params.require(:json).permit(:type, :data)
    end
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/views/jsons/_form.html.erb
<%= form_for(@json) do |f| %>
  <% if @json.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@json.errors.count, "error") %> prohibited this json from being saved:</h2>

      <ul>
      <% @json.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jsons/edit.html.erb
<h1>Editing Json</h1>

<%= render 'form' %>

<%= link_to 'Show', @json %> |
<%= link_to 'Back', jsons_path %>

app/views/jsons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jsons</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jsons.each do |json| %>
      <tr>
        <td><%= json.type %></td>
        <td><%= json.data %></td>
        <td><%= link_to 'Show', json %></td>
        <td><%= link_to 'Edit', edit_json_path(json) %></td>
        <td><%= link_to 'Destroy', json, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Json', new_json_path %>

app/views/jsons/new.html.erb
<h1>New Json</h1>

<%= render 'form' %>

<%= link_to 'Back', jsons_path %>

app/views/jsons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @json.type %>
</p>

<p>
  <strong>Data:</strong>
  <%= @json.data %>
</p>

<%= link_to 'Edit', edit_json_path(@json) %> |
<%= link_to 'Back', jsons_path %>